### ISSUE TITLE
What's the roadmap of the nanorpc

### ISSUE THREAD

**Issue by kuncao** [sroycode/nanorpc#2]
Hi Mr. sroycode,
What's the roadmap of the nanorpc?
This poject has not update for about 3 years.
nanomsg has published  1.0 version.
What's your opion for  nanomsg + protobuf  vs  zeromq + protobuf  as RPC framework.
Thanks a lot.

**Comment by sroycode** [comment]
I will take a fresh look at this in Dec. The zqrpc code too has gone through quite a bit of cleanup which I have not been able to post to github.
